#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-accessors-smart
Version  : 1.2
Release  : 1
URL      : https://repo1.maven.org/maven2/net/minidev/accessors-smart/1.2/accessors-smart-1.2-sources.jar
Source0  : https://repo1.maven.org/maven2/net/minidev/accessors-smart/1.2/accessors-smart-1.2-sources.jar
Source1  : https://repo1.maven.org/maven2/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar
Source2  : https://repo1.maven.org/maven2/net/minidev/accessors-smart/1.2/accessors-smart-1.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-accessors-smart-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-accessors-smart package.
Group: Data

%description data
data components for the mvn-accessors-smart package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/minidev/accessors-smart/1.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/net/minidev/accessors-smart/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/minidev/accessors-smart/1.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/minidev/accessors-smart/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/minidev/accessors-smart/1.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/minidev/accessors-smart/1.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2-sources.jar
/usr/share/java/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar
/usr/share/java/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.pom
